version: "3.1"
services:
  webserver:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mariadb
    ports:
      - ${HOST_PORT}:80
    environment:
      DB_HOST: mariadb
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./site:/var/www/html

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${PROJECT_NAME}:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_HOST_PORT}:80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USERNAME: ${MYSQL_USER}
      UPLOAD_LIMIT: 300M

volumes:
  ${PROJECT_NAME}:
